import 'package:flutter/material.dart';

class PrivacyPolicyPage extends StatelessWidget {
  const PrivacyPolicyPage({super.key});

  @override
  Widget build(BuildContext context) {

    final screenWidth = MediaQuery.sizeOf(context).width;

    return Scaffold(
      resizeToAvoidBottomInset: true,
      backgroundColor: Colors.white,
      appBar: AppBar(
        forceMaterialTransparency: true,
        title: const Text('Privacy Policy'),
        centerTitle: true,
      ),
      body: SingleChildScrollView(
        child: Padding(
          padding: EdgeInsets.only(
            left: screenWidth * 0.08,
            right: screenWidth * 0.08,
            top: screenWidth * 0.05,
          ),
          child: const Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: <Widget>[
              Text('Privacy Policy'),
              Text('Last updated: October 02, 2024'),
              Text('This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.'),
              Text('Interpretation and Definitions'),
              Text('Interpretation'),
              Text('The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.'),
              Text('Definitions'),
              Text('For the purposes of this Privacy Policy:'),
              Text('Account means a unique account created for You to access our Service or parts of our Service.'),
              Text('Affiliate means an entity that controls, is controlled by or is under common control with a party, where &quot;control&quot; means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.'),
              Text('Application refers to FinEdger, the software program provided by the Company.'),
              Text('Company(referred to as either "the Company", "We", "Us" "Our" in this Agreement) refers to FinEdger.'),
              Text('Country refers to:  Philippines'),
              Text('Device means any device that can access the Service such as a computer, a cellphone or a digital tablet.'),
              Text('Personal Data is any information that relates to an identified or identifiable individual.'),
              Text('Service refers to the Application.'),
              Text('Service Provider means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.'),
              Text('Third-party Social Media Service refers to any website or any social network website through which a User can log in or create an account to use the Service.'),
              Text('Usage Data refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).'),
              Text('You</strong> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.'),
              Text('Collecting and Using Your Personal Data'),
              Text('Types of Data Collected'),
              Text('Personal Data'),
              Text('While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:'),
              Text('Email address'),
              Text('First name and last name'),
              Text('Phone number'),
              Text('Usage Data'),
              Text('Usage Data'),
              Text('Usage Data is collected automatically when using the Service.'),
              Text('Usage Data may include information such as Your Device\'s Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.'),
              Text('When You access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile device You use, Your mobile device unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data.'),
              Text('We may also collect information that Your browser sends whenever You visit our Service or when You access the Service by or through a mobile device.'),
            ],
          ),
        ),
      ),
    );
  }
}
